### ISSUE TITLE
Ability to turn off PR template feature

### ISSUE THREAD

**Issue by rjmunro** [RobQuistNL/chrome-github-jira#22]
The projects I work on have their own per-project custom PR templates in github ([using these instructions](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)). When I have this plugin installed, they get overwritten with the PR template configured in the plugin. I tried leaving the PR template option blank, but this still overwrote my project PR template with a blank template.

It would be great if this feature could be turned off. Even better if the template acceptance criteria substitution would still work with the template stored in github, rather than only with the template stored in this project.

**Comment by RobQuistNL** [comment]
Oh, coolio! That looks like a new feature in Github. I have been using GitLab for some main projects lately, but this is definately a good addition. Like you said, combining these two would be even better.

**Comment by zhaochy1990** [comment]
The same problem struggled me.

**Comment by RobQuistNL** [comment]
Added the option in 9f06e7a, will try to get 1.2.0 published soon!
