### ISSUE TITLE
Can't login to JIRA instance due to CORS issues

### ISSUE THREAD

**Issue by sergiofbsilva** [RobQuistNL/chrome-github-jira#24]
Due to cross origin requests to the jira instance it is necessary to update the ajax requests to use withCredentials.
More over it is necessary to setup CORS locally if you don't want to whitelist chrome-extensions in JIRA administration panel (which I think it is not possible)

**Comment by RobQuistNL** [comment]
Please let me know if this is fixed with 9f06e7a - will be in 1.2.0.
