### ISSUE TITLE
chrome.storage API change bug?

### ISSUE THREAD

**Issue by xgqfrms** [RobQuistNL/chrome-github-jira#26]
# chrome.storage API change bug?

https://github.com/RobQuistNL/chrome-github-jira/blob/master/src/options.js

> `chrome.storage.sync.get({key}, () => {}}` => `chrome.storage.sync.get(['key'], () => {})`

> Object param changed to Array param ???

## storage API

https://developer.chrome.com/extensions/storage#using-sync

> To store user data for your extension, you can use either `storage.sync`, or `storage.local`

```js

// storage.sync
chrome.storage.sync.set({key: value}, function() {
    console.log('Value is set to ' + value);
});

chrome.storage.sync.get(['key'], function(result) {
    console.log('Value currently is ' + result.key);
});

```

```js
// storage.local:

chrome.storage.local.set({key: value}, function() {
    console.log('Value is set to ' + value);
});

chrome.storage.local.get(['key'], function(result) {
    console.log('Value currently is ' + result.key);
});

```

**Comment by RobQuistNL** [comment]
I'm not sure what you mean? Closing this - if its important - feel free to ping me.
