### ISSUE TITLE
This extension violates the Chrome Web Store policy

### ISSUE THREAD

**Issue by fegbers** [RobQuistNL/chrome-github-jira#44]
Hi,

Is this great extension still maintained?
The extension has been disabled by edge due to violations of Chrome Web Store policy (but not clear what kind of violations..). For this reason, the extension is also no longer available in the [webstore](https://chrome.google.com/webstore/detail/github-jira-integration/faenbbkpfnklhncjianlfllkfekgghih).
Is there any plan to fix the problem and put the extension back in the webstore?

Greetings

**Comment by RobQuistNL** [comment]
Heya, I think I did see something about that! It had something to do with the access that it requests.. Google changed their policy on that. Let me check

**Comment by fegbers** [comment]
> Heya, I think I did see something about that! It had something to do with the access that it requests.. Google changed their policy on that. Let me check

Perfect, thanks

**Comment by fegbers** [comment]
> Heya, I think I did see something about that! It had something to do with the access that it requests.. Google changed their policy on that. Let me check

Hey - Any news? Thanks :)

**Comment by RobQuistNL** [comment]
Sorry, my bad.. Crazy days here lately.

I've resubmitted the request to Google and it should be in their hands now to verify the extension.

If they allow it, it should be back online!

Good to see all the thumbs up here, didn't know it was being used this much :)

**Comment by fegbers** [comment]
The extension is back. Thanks for your quick action! 🎊

**Comment by RobQuistNL** [comment]
Awesome! Sorry it took so long... Apparantly my "Privacy Policy" wasn't good, even while all this data never passes through any of my servers. Thanks for notifying me!

**Comment by fegbers** [comment]
> Awesome! Sorry it took so long... Apparantly my "Privacy Policy" wasn't good, even while all this data never passes through any of my servers. Thanks for notifying me!

Don't worry, we all do it in our spare time! Right now, I'm just glad it's working again. I really missed that 😃
