### ISSUE TITLE
Add support for custom Jira url

### ISSUE THREAD

**Issue by exadeci** [RobQuistNL/chrome-github-jira#45]
My organisation uses their own instance of Jira with a unique url, it would be great if we could add a new url to the list of urls allowed for this Extension.

This extension supports it: https://chrome.google.com/webstore/detail/jira-hotlinker/lbifpcpomdegljfpfhgfcjdabbeallhk/related
**But I much prefer your extension.**

**Comment by RobQuistNL** [comment]
You should be able to set the Jira URL in the extension options - or is that not what you mean?

**Comment by exadeci** [comment]
@RobQuistNL The extension is only allowed to access atlassian and GitHub domains and all their subdomains, my JIRA instance is on a custom domain so the extension doesn't have access permissions

**Comment by RobQuistNL** [comment]
Hmm, I don't really know how to do this out of the box.. You could bake your own extension and change the metadata I think, but I don't know what a good solution would be.

**Comment by exadeci** [comment]
@RobQuistNL That's why I had linked the other extension that does it dynamically it's open source too
https://github.com/helmus/Jira-Hot-Linker

But I understand that if no one else in interested in this feature it might not feel worth the time.

**Comment by RobQuistNL** [comment]
Ah, I didn't see any links to sourcecode in that URL you posted initially. 

I started on a PR but its far from done - I just collected some of the information there; https://github.com/RobQuistNL/chrome-github-jira/pull/46

**Comment by exadeci** [comment]
Oh awesome thanks!
